### PR TITLE
Update cover image

### PR DESCRIPTION
**Pull request by olearycrew**
This updates the cover image to remove the white line on the right side of the image

### CODE REVIEW

**Comment by olearycrew** [comment]
@ehrishirajsharma @ehsandeep

**Comment by ehrishirajsharma** [comment]
👀 

https://www.youtube.com/watch?v=1iFghM5fIig&ab_channel=HilariousFamilyGuy1

**Comment by ehrishirajsharma** [comment]
@olearycrew did you compress the image too? looks a bit blurry compared to the original one...

**Comment by olearycrew** [comment]
I didn't - I got it from Michael. Let me check with him.

**Pull request closed without merging**
